version: '3.8'

services:
    postgres:
        image: postgres:13
        container_name: postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: development
        volumes:
            - ./docker/database:/var/lib/postgresql/data
        ports:
            - '5432:5432'

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - '8080:80'
        depends_on:
            - postgres

volumes:
    database:
